name: "TEST WORKFLOW"

on:
  workflow_dispatch:
    inputs:
      build_application_required:
        description: "Build application?"
        required: true
        default: true
        type: boolean
      team_a:
        description: "Market: PT"
        required: true
        default: true
        type: boolean
      team_b:
        description: "Market: ES"
        required: true
        default: true
        type: boolean
      team_c:
        description: "Market: IT"
        required: true
        default: true
        type: boolean
  workflow_call:
    inputs:
      build_application_required:
        required: true
        default: true
        type: boolean
      team_a:
        default: true
        type: boolean
      team_b:
        default: true
        type: boolean
      team_c:
        default: true
        type: boolean

env:
  TEAM_A: ${{ inputs.team_a }}
  TEAM_B: ${{ inputs.team_b }}
  TEAM_C: ${{ inputs.team_c }}

jobs:
  print_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Print Teams
        run: |
          echo "Team A: $TEAM_A"
          echo "Team B: $TEAM_B"
          echo "Team C: $TEAM_C"
