name: "TEST WORKFLOW"

on:
  workflow_dispatch:
    inputs:
      build_application_required:
        description: "Build application?"
        required: true
        default: true
        type: boolean
      additional_teams:
        description: JSON of additional options
        type: string
        default: '{}'
        required: true

env:
  TEAM_A: ${{ fromJson(inputs.additional_teams).team_a}}
  TEAM_B: ${{ fromJson(inputs.additional_teams).team_b}}
  TEAM_C: ${{ fromJson(inputs.additional_teams).team_c}}
  TEAM_D: ${{ fromJson(inputs.additional_teams).team_d}}
jobs:
  print_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Print Teams
        run: |
          echo "Team A: $TEAM_A"
          echo "Team B: $TEAM_B"
          echo "Team C: $TEAM_C"
          echo "Team D: $TEAM_D"
